/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

const projectId = "evffhpojvwldwsvgnzxb";
const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImV2ZmZocG9qdndsZHdzdmduenhiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE5MzQwNTAsImV4cCI6MjA3NzUxMDA1MH0.t6MGNUnwZJC0TE9RYjQIviXWUfp_lIZtpXe3l1N-xi8";

// Create Supabase client (will be initialized after supabase library loads)
// Note: The CDN exposes the library as a global 'supabase' object
// We store our client instance in window.supabaseClient
let supabaseClient = null;

function initSupabase() {
  // The Supabase CDN from jsdelivr exposes it as a global
  // Check multiple possible global names
  let supabaseLib = null;
  
  if (typeof window.supabase !== 'undefined') {
    supabaseLib = window.supabase;
  } else if (typeof supabase !== 'undefined') {
    supabaseLib = supabase;
  } else if (typeof window.supabaseLib !== 'undefined') {
    supabaseLib = window.supabaseLib;
  }
  
  if (supabaseLib && supabaseLib.createClient) {
    try {
      supabaseClient = supabaseLib.createClient(
        `https://${projectId}.supabase.co`,
        publicAnonKey
      );
      window.supabaseClient = supabaseClient;
      console.log('Supabase client initialized successfully');
    } catch (error) {
      console.error('Error creating Supabase client:', error);
    }
  } else {
    console.warn('Supabase library not found, retrying...');
    // Retry after a short delay
    setTimeout(() => {
      initSupabase();
    }, 500);
  }
}

// Make supabaseClient available globally
// Other scripts should use window.supabaseClient

// Initialize Supabase - wait for library to load
// The UMD build exposes it as a global, but we need to wait for the script to load
function waitForSupabase() {
  // Check if Supabase library is loaded
  if (typeof window.supabase !== 'undefined' || typeof supabase !== 'undefined') {
    initSupabase();
  } else {
    // Retry after a short delay
    setTimeout(waitForSupabase, 100);
  }
}

// Start waiting when DOM is ready
if (document.readyState === 'loading') {
  document.addEventListener('DOMContentLoaded', waitForSupabase);
} else {
  waitForSupabase();
}

